// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contracts.sql

package dbgen

import (
	"context"
)

const deleteContract = `-- name: DeleteContract :exec
DELETE FROM contract WHERE id = $1
`

func (q *Queries) DeleteContract(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteContract, id)
	return err
}

const insertContract = `-- name: InsertContract :one
INSERT INTO contract (name, number, home_resort, annual_points, use_year_month, term_years, purchase_price_cents, closing_costs_cents)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertContractParams struct {
	Name               string
	Number             string
	HomeResort         string
	AnnualPoints       int32
	UseYearMonth       int32
	TermYears          int32
	PurchasePriceCents int64
	ClosingCostsCents  int64
}

func (q *Queries) InsertContract(ctx context.Context, arg InsertContractParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertContract,
		arg.Name,
		arg.Number,
		arg.HomeResort,
		arg.AnnualPoints,
		arg.UseYearMonth,
		arg.TermYears,
		arg.PurchasePriceCents,
		arg.ClosingCostsCents,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listContracts = `-- name: ListContracts :many
SELECT id, name, number, home_resort, annual_points, use_year_month, term_years, purchase_price_cents, closing_costs_cents
FROM contract
ORDER BY id
`

func (q *Queries) ListContracts(ctx context.Context) ([]Contract, error) {
	rows, err := q.db.QueryContext(ctx, listContracts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contract
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Number,
			&i.HomeResort,
			&i.AnnualPoints,
			&i.UseYearMonth,
			&i.TermYears,
			&i.PurchasePriceCents,
			&i.ClosingCostsCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContract = `-- name: UpdateContract :exec
UPDATE contract
SET name = $1, number = $2, home_resort = $3, annual_points = $4, use_year_month = $5,
    term_years = $6, purchase_price_cents = $7, closing_costs_cents = $8
WHERE id = $9
`

type UpdateContractParams struct {
	Name               string
	Number             string
	HomeResort         string
	AnnualPoints       int32
	UseYearMonth       int32
	TermYears          int32
	PurchasePriceCents int64
	ClosingCostsCents  int64
	ID                 int64
}

func (q *Queries) UpdateContract(ctx context.Context, arg UpdateContractParams) error {
	_, err := q.db.ExecContext(ctx, updateContract,
		arg.Name,
		arg.Number,
		arg.HomeResort,
		arg.AnnualPoints,
		arg.UseYearMonth,
		arg.TermYears,
		arg.PurchasePriceCents,
		arg.ClosingCostsCents,
		arg.ID,
	)
	return err
}
