// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: distribute.sql

package dbgen

import (
	"context"
	"database/sql"
)

const countAllocationFor = `-- name: CountAllocationFor :one
SELECT COUNT(1) FROM entries
WHERE contract_id = $1 AND kind = $2 AND use_year = $3
`

type CountAllocationForParams struct {
	ContractID sql.NullInt64
	Kind       string
	UseYear    int32
}

func (q *Queries) CountAllocationFor(ctx context.Context, arg CountAllocationForParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllocationFor, arg.ContractID, arg.Kind, arg.UseYear)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const latestAllocationYear = `-- name: LatestAllocationYear :one
SELECT use_year FROM entries
WHERE contract_id = $1 AND kind = $2
ORDER BY use_year DESC LIMIT 1
`

type LatestAllocationYearParams struct {
	ContractID sql.NullInt64
	Kind       string
}

func (q *Queries) LatestAllocationYear(ctx context.Context, arg LatestAllocationYearParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, latestAllocationYear, arg.ContractID, arg.Kind)
	var use_year int32
	err := row.Scan(&use_year)
	return use_year, err
}

const useYearSummaries = `-- name: UseYearSummaries :many
SELECT use_year, COALESCE(SUM(allotted), 0)::bigint AS allotted, COALESCE(SUM(used), 0)::bigint AS used
FROM entries
GROUP BY use_year
ORDER BY use_year
`

type UseYearSummariesRow struct {
	UseYear  int32
	Allotted int64
	Used     int64
}

func (q *Queries) UseYearSummaries(ctx context.Context) ([]UseYearSummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, useYearSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UseYearSummariesRow
	for rows.Next() {
		var i UseYearSummariesRow
		if err := rows.Scan(&i.UseYear, &i.Allotted, &i.Used); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
