// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dues.sql

package dbgen

import (
	"context"
)

const deleteDuesRate = `-- name: DeleteDuesRate :exec
DELETE FROM dues_rate WHERE use_year = $1
`

func (q *Queries) DeleteDuesRate(ctx context.Context, useYear int32) error {
	_, err := q.db.ExecContext(ctx, deleteDuesRate, useYear)
	return err
}

const listDuesRates = `-- name: ListDuesRates :many
SELECT use_year, rate_micros
FROM dues_rate
ORDER BY use_year
`

func (q *Queries) ListDuesRates(ctx context.Context) ([]DuesRate, error) {
	rows, err := q.db.QueryContext(ctx, listDuesRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DuesRate
	for rows.Next() {
		var i DuesRate
		if err := rows.Scan(&i.UseYear, &i.RateMicros); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDuesRate = `-- name: UpsertDuesRate :exec
INSERT INTO dues_rate (use_year, rate_micros) VALUES ($1, $2)
ON CONFLICT (use_year) DO UPDATE SET rate_micros = EXCLUDED.rate_micros
`

type UpsertDuesRateParams struct {
	UseYear    int32
	RateMicros int64
}

func (q *Queries) UpsertDuesRate(ctx context.Context, arg UpsertDuesRateParams) error {
	_, err := q.db.ExecContext(ctx, upsertDuesRate, arg.UseYear, arg.RateMicros)
	return err
}
