// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const deleteEntriesForStay = `-- name: DeleteEntriesForStay :exec
DELETE FROM entry
 WHERE id IN (SELECT entry_id FROM trip_stay WHERE trip_stay.id = $1 AND entry_id IS NOT NULL)
`

func (q *Queries) DeleteEntriesForStay(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntriesForStay, id)
	return err
}

const deleteEntriesForTrip = `-- name: DeleteEntriesForTrip :exec
DELETE FROM entry
 WHERE id IN (SELECT entry_id FROM trip_stay WHERE trip_id = $1 AND entry_id IS NOT NULL)
`

func (q *Queries) DeleteEntriesForTrip(ctx context.Context, tripID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntriesForTrip, tripID)
	return err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entry WHERE id = $1
`

func (q *Queries) DeleteEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntry, id)
	return err
}

const insertEntry = `-- name: InsertEntry :one
INSERT INTO entry (use_year, date, description, kind, allotted, used, tag, contract_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertEntryParams struct {
	UseYear     int32
	Date        string
	Description string
	Kind        string
	Allotted    int32
	Used        int32
	Tag         string
	ContractID  sql.NullInt64
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertEntry,
		arg.UseYear,
		arg.Date,
		arg.Description,
		arg.Kind,
		arg.Allotted,
		arg.Used,
		arg.Tag,
		arg.ContractID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, use_year, date, description, kind, allotted, used, tag, contract_id
FROM entry
ORDER BY date, id
`

func (q *Queries) ListEntries(ctx context.Context) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.UseYear,
			&i.Date,
			&i.Description,
			&i.Kind,
			&i.Allotted,
			&i.Used,
			&i.Tag,
			&i.ContractID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entry
SET use_year = $1, date = $2, description = $3, kind = $4, allotted = $5, used = $6, tag = $7, contract_id = $8
WHERE id = $9
`

type UpdateEntryParams struct {
	UseYear     int32
	Date        string
	Description string
	Kind        string
	Allotted    int32
	Used        int32
	Tag         string
	ContractID  sql.NullInt64
	ID          int64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateEntry,
		arg.UseYear,
		arg.Date,
		arg.Description,
		arg.Kind,
		arg.Allotted,
		arg.Used,
		arg.Tag,
		arg.ContractID,
		arg.ID,
	)
	return err
}
