// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type Contract struct {
	ID                 int64
	Name               string
	Number             string
	HomeResort         string
	AnnualPoints       int32
	UseYearMonth       int32
	TermYears          int32
	PurchasePriceCents int64
	ClosingCostsCents  int64
}

type DuesRate struct {
	UseYear    int32
	RateMicros int64
}

type Entry struct {
	ID          int64
	UseYear     int32
	Date        string
	Description string
	Kind        string
	Allotted    int32
	Used        int32
	Tag         string
	ContractID  sql.NullInt64
}
