// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM trip WHERE id = $1
`

func (q *Queries) DeleteTrip(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrip, id)
	return err
}

const deleteTripStay = `-- name: DeleteTripStay :exec
DELETE FROM trip_stay WHERE id = $1
`

func (q *Queries) DeleteTripStay(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTripStay, id)
	return err
}

const getTrip = `-- name: GetTrip :one
SELECT id, name, start_date, end_date, min_nights, budget_override, filter_mode, exclude_resorts, exclude_room_types
FROM trip
WHERE id = $1
`

func (q *Queries) GetTrip(ctx context.Context, id int64) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTrip, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.MinNights,
		&i.BudgetOverride,
		&i.FilterMode,
		&i.ExcludeResorts,
		&i.ExcludeRoomTypes,
	)
	return i, err
}

const insertTrip = `-- name: InsertTrip :one
INSERT INTO trip (name, start_date, end_date, min_nights, budget_override, filter_mode, exclude_resorts, exclude_room_types)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertTripParams struct {
	Name             string
	StartDate        time.Time
	EndDate          time.Time
	MinNights        int32
	BudgetOverride   sql.NullInt32
	FilterMode       string
	ExcludeResorts   string
	ExcludeRoomTypes string
}

func (q *Queries) InsertTrip(ctx context.Context, arg InsertTripParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTrip,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.MinNights,
		arg.BudgetOverride,
		arg.FilterMode,
		arg.ExcludeResorts,
		arg.ExcludeRoomTypes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTripStay = `-- name: InsertTripStay :one
INSERT INTO trip_stay (trip_id, resort, room_type, view, check_in, check_out, nights, points, quote_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertTripStayParams struct {
	TripID    int64
	Resort    string
	RoomType  string
	View      string
	CheckIn   time.Time
	CheckOut  time.Time
	Nights    int32
	Points    int32
	QuoteHash string
}

func (q *Queries) InsertTripStay(ctx context.Context, arg InsertTripStayParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTripStay,
		arg.TripID,
		arg.Resort,
		arg.RoomType,
		arg.View,
		arg.CheckIn,
		arg.CheckOut,
		arg.Nights,
		arg.Points,
		arg.QuoteHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTripStayEntry = `-- name: InsertTripStayEntry :exec
INSERT INTO trip_stay_entry (trip_stay_id, entry_id)
VALUES ($1, $2)
`

type InsertTripStayEntryParams struct {
	TripStayID int64
	EntryID    int64
}

func (q *Queries) InsertTripStayEntry(ctx context.Context, arg InsertTripStayEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertTripStayEntry, arg.TripStayID, arg.EntryID)
	return err
}

const listTripStayEntryIDsForTrip = `-- name: ListTripStayEntryIDsForTrip :many
SELECT tse.trip_stay_id, tse.entry_id
FROM trip_stay_entry tse
JOIN trip_stay ts ON ts.id = tse.trip_stay_id
WHERE ts.trip_id = $1
ORDER BY tse.trip_stay_id, tse.entry_id
`

type ListTripStayEntryIDsForTripRow struct {
	TripStayID int64
	EntryID    int64
}

// Every (trip_stay_id, entry_id) link for tripID's stays, in one query —
// Store.ListStays groups these by trip_stay_id in Go rather than each stay
// issuing its own lookup.
func (q *Queries) ListTripStayEntryIDsForTrip(ctx context.Context, tripID int64) ([]ListTripStayEntryIDsForTripRow, error) {
	rows, err := q.db.QueryContext(ctx, listTripStayEntryIDsForTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripStayEntryIDsForTripRow
	for rows.Next() {
		var i ListTripStayEntryIDsForTripRow
		if err := rows.Scan(&i.TripStayID, &i.EntryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripStays = `-- name: ListTripStays :many
SELECT id, trip_id, resort, room_type, view, check_in, check_out, nights, points, quote_hash
FROM trip_stay
WHERE trip_id = $1
ORDER BY check_in, id
`

func (q *Queries) ListTripStays(ctx context.Context, tripID int64) ([]TripStay, error) {
	rows, err := q.db.QueryContext(ctx, listTripStays, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripStay
	for rows.Next() {
		var i TripStay
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Resort,
			&i.RoomType,
			&i.View,
			&i.CheckIn,
			&i.CheckOut,
			&i.Nights,
			&i.Points,
			&i.QuoteHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrips = `-- name: ListTrips :many
SELECT id, name, start_date, end_date, min_nights, budget_override, filter_mode, exclude_resorts, exclude_room_types
FROM trip
ORDER BY start_date, id
`

func (q *Queries) ListTrips(ctx context.Context) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, listTrips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.MinNights,
			&i.BudgetOverride,
			&i.FilterMode,
			&i.ExcludeResorts,
			&i.ExcludeRoomTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrip = `-- name: UpdateTrip :exec
UPDATE trip
SET name = $1, start_date = $2, end_date = $3, min_nights = $4, budget_override = $5, filter_mode = $6, exclude_resorts = $7, exclude_room_types = $8
WHERE id = $9
`

type UpdateTripParams struct {
	Name             string
	StartDate        time.Time
	EndDate          time.Time
	MinNights        int32
	BudgetOverride   sql.NullInt32
	FilterMode       string
	ExcludeResorts   string
	ExcludeRoomTypes string
	ID               int64
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) error {
	_, err := q.db.ExecContext(ctx, updateTrip,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.MinNights,
		arg.BudgetOverride,
		arg.FilterMode,
		arg.ExcludeResorts,
		arg.ExcludeRoomTypes,
		arg.ID,
	)
	return err
}
