-- This is a VERBATIM copy of internal/ledger/seed.sql as it stood right
-- before the switch to goose migrations (see internal/ledger/migrations/).
-- Paired with legacy_schema.sql, it reproduces the exact state of the
-- percival deployment for migrate_test.go's baseline-adoption rehearsal.
--
-- DO NOT edit this file to match 00002_seed_dues_rates.sql or any later
-- migration. It must stay a frozen snapshot of what boot-time re-exec
-- already put in the real database, not what the migrations now describe.
-- Reference data seeded on every process start (internal/ledger/store.go's
-- Open, after schema.sql). Unlike schema.sql this is DML, not DDL — it must
-- stay idempotent under a *table-level* guard, not a per-row ON CONFLICT:
-- an operator who deletes a seeded dues year through the UI must see it
-- stay deleted across a restart, not get resurrected here.
INSERT INTO dues_rates (use_year, rate_micros)
SELECT * FROM (VALUES
    (2019, 6385000),
    (2020, 6561600),
    (2021, 6811800),
    (2022, 7007700),
    (2023, 7333200),
    (2024, 7574000),
    (2025, 7929800),
    (2026, 8223500)
) AS seeded_dues_rates(use_year, rate_micros)
WHERE NOT EXISTS (SELECT 1 FROM dues_rates);
