-- This is a VERBATIM copy of internal/ledger/schema.sql as it stood right
-- before the switch to goose migrations (see internal/ledger/migrations/).
-- It exists so migrate_test.go can rehearse goose's baseline migration
-- (00001_initial.sql) against a database that looks exactly like the
-- percival deployment: a schema with no goose_db_version table, produced
-- by re-running this file (and legacy_seed.sql) on every boot the old way.
--
-- DO NOT edit this file to match 00001_initial.sql or any later migration.
-- The whole point of TestOpen_BaselineOverPreExistingDatabase is proving
-- that goose's baseline correctly recognizes and adopts *this* — the real,
-- frozen, pre-migration shape of the deployed database — without trying to
-- recreate or alter anything in it. If this file ever drifts to match the
-- migrations, the test stops testing the thing it exists to test.
CREATE TABLE IF NOT EXISTS contracts (
    id                   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name                 TEXT    NOT NULL,
    number               TEXT    NOT NULL DEFAULT '',
    home_resort          TEXT    NOT NULL DEFAULT '',
    annual_points        INTEGER NOT NULL DEFAULT 0,
    use_year_month       INTEGER NOT NULL DEFAULT 1,
    term_years           INTEGER NOT NULL DEFAULT 0,
    purchase_price_cents BIGINT  NOT NULL DEFAULT 0,
    closing_costs_cents  BIGINT  NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS entries (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    use_year    INTEGER NOT NULL,
    date        TEXT    NOT NULL,            -- ISO date (YYYY-MM-DD)
    description TEXT    NOT NULL DEFAULT '',
    kind        TEXT    NOT NULL,
    allotted    INTEGER NOT NULL DEFAULT 0,
    used        INTEGER NOT NULL DEFAULT 0,
    tag         TEXT    NOT NULL DEFAULT '',
    contract_id BIGINT REFERENCES contracts(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_entries_order ON entries(date, id);
CREATE INDEX IF NOT EXISTS idx_entries_use_year ON entries(use_year);

CREATE TABLE IF NOT EXISTS dues_rates (
    use_year    INTEGER PRIMARY KEY,
    rate_micros BIGINT  NOT NULL
);

-- Columns added after the initial release. Nothing below this comment may
-- ever be removed: schema.sql is re-executed as a single multi-statement
-- Exec on every process start against the one deployed database, and there
-- is no migration tool — a column change must be expressed both in the
-- CREATE TABLE above (for a fresh database) and here (for the deployed
-- one), and every statement here must stay idempotent forever.
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS term_years           INTEGER NOT NULL DEFAULT 0;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS purchase_price_cents BIGINT  NOT NULL DEFAULT 0;
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS closing_costs_cents  BIGINT  NOT NULL DEFAULT 0;
